export * from './base.entity';
export * from './faculty.entity';
export * from './user.entity';
export * from './student.entity';
export * from './semester.entity';
export * from './topic.entity';
export * from './studentSubject.entity';
export * from './student-topic.entity';
export * from './topic-semester.entity';
