export * from './teacher.controller';
export * from './faculty.controller';
export * from './student.controller';
export * from './auth.controller';
export * from './semester.controller';
export * from './student-topic.controller';
export * from './topic.controller';
export * from './super-admin.controller';
export * from './super-teacher.controller';
